#!/bin/bash

# =============================================================================
# Watch Party API - Automated Testing Script
# =============================================================================
# This script runs comprehensive API tests using Newman (Postman CLI)
# 
# Prerequisites:
# - Node.js and npm installed
# - Newman installed globally: npm install -g newman
# - Django server running on localhost:8000
# - All environment variables configured
# =============================================================================

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
POSTMAN_DIR="/workspaces/watch-party/postman"
RESULTS_DIR="$POSTMAN_DIR/results"
LOG_FILE="$RESULTS_DIR/test-execution.log"
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")

# Create results directory
mkdir -p "$RESULTS_DIR"

# Logging function
log() {
    echo -e "$1" | tee -a "$LOG_FILE"
}

# Check prerequisites
check_prerequisites() {
    log "${BLUE}🔍 Checking prerequisites...${NC}"
    
    # Check if Newman is installed
    if ! command -v newman &> /dev/null; then
        log "${RED}❌ Newman is not installed. Installing...${NC}"
        npm install -g newman
    else
        log "${GREEN}✅ Newman is installed${NC}"
    fi
    
    # Check if newman-reporter-html is installed
    if ! npm list -g newman-reporter-html &> /dev/null; then
        log "${YELLOW}⚠️  Installing HTML reporter...${NC}"
        npm install -g newman-reporter-html
    fi
    
    # Check if Django server is running
    log "${BLUE}🔍 Checking Django server...${NC}"
    if curl -f -s http://localhost:8000/health/ > /dev/null; then
        log "${GREEN}✅ Django server is running${NC}"
    else
        log "${RED}❌ Django server is not responding. Please start the server:${NC}"
        log "${YELLOW}cd /workspaces/watch-party/back-end && python manage.py runserver${NC}"
        exit 1
    fi
    
    # Check Redis connection
    log "${BLUE}🔍 Checking Redis connection...${NC}"
    if redis-cli ping &> /dev/null; then
        log "${GREEN}✅ Redis is running${NC}"
    else
        log "${YELLOW}⚠️  Redis is not running. Some tests may fail.${NC}"
    fi
}

# Run a specific test collection
run_collection() {
    local collection_name="$1"
    local collection_file="$2"
    local environment_file="$3"
    local output_prefix="$4"
    
    log "${BLUE}🧪 Running $collection_name tests...${NC}"
    
    # Run Newman with multiple reporters
    newman run "$collection_file" \
        -e "$environment_file" \
        --reporters cli,html,json \
        --reporter-html-export "$RESULTS_DIR/${output_prefix}-report-${TIMESTAMP}.html" \
        --reporter-json-export "$RESULTS_DIR/${output_prefix}-results-${TIMESTAMP}.json" \
        --timeout-request 10000 \
        --timeout-script 5000 \
        --delay-request 100 \
        --verbose \
        2>&1 | tee -a "$LOG_FILE"
    
    local exit_code=${PIPESTATUS[0]}
    
    if [ $exit_code -eq 0 ]; then
        log "${GREEN}✅ $collection_name tests passed${NC}"
        return 0
    else
        log "${RED}❌ $collection_name tests failed (exit code: $exit_code)${NC}"
        return $exit_code
    fi
}

# Generate summary report
generate_summary() {
    log "${BLUE}📊 Generating test summary...${NC}"
    
    local summary_file="$RESULTS_DIR/test-summary-${TIMESTAMP}.md"
    
    cat > "$summary_file" << EOF
# Watch Party API Test Summary

**Test Execution Date**: $(date)
**Environment**: Local Development
**Total Collections Tested**: 3

## Test Results

### 1. Basic API Collection
- **Status**: $([ -f "$RESULTS_DIR/api-results-${TIMESTAMP}.json" ] && echo "✅ Completed" || echo "❌ Failed")
- **Report**: [View HTML Report](./api-report-${TIMESTAMP}.html)

### 2. Advanced Testing Suite
- **Status**: $([ -f "$RESULTS_DIR/advanced-results-${TIMESTAMP}.json" ] && echo "✅ Completed" || echo "❌ Failed")
- **Report**: [View HTML Report](./advanced-report-${TIMESTAMP}.html)

### 3. Complete Flow Test
- **Status**: $([ -f "$RESULTS_DIR/flow-results-${TIMESTAMP}.json" ] && echo "✅ Completed" || echo "❌ Failed")
- **Report**: [View HTML Report](./flow-report-${TIMESTAMP}.html)

## Quick Links
- [Execution Log](./test-execution.log)
- [All Reports Directory](./)

## Next Steps
1. Review any failed tests in the HTML reports
2. Check the execution log for detailed error messages
3. Fix any issues found and re-run tests
4. Update API documentation if needed

---
Generated by Watch Party API Test Automation Script
EOF

    log "${GREEN}✅ Summary report generated: $summary_file${NC}"
}

# Main execution function
main() {
    log "${BLUE}🚀 Starting Watch Party API Test Suite${NC}"
    log "${BLUE}Timestamp: $(date)${NC}"
    log "${BLUE}Results will be saved in: $RESULTS_DIR${NC}"
    log ""
    
    # Check prerequisites
    check_prerequisites
    log ""
    
    # Define file paths
    local env_file="$POSTMAN_DIR/environments/Local-Development.postman_environment.json"
    local basic_collection="$POSTMAN_DIR/Watch-Party-API-Collection.json"
    local advanced_collection="$POSTMAN_DIR/Watch-Party-Advanced-Tests.json"
    local flow_collection="$POSTMAN_DIR/Watch-Party-Complete-Flow.json"
    
    # Initialize counters
    local total_tests=0
    local passed_tests=0
    local failed_tests=0
    
    # Run Basic API Collection
    if run_collection "Basic API" "$basic_collection" "$env_file" "api"; then
        ((passed_tests++))
    else
        ((failed_tests++))
    fi
    ((total_tests++))
    log ""
    
    # Run Advanced Testing Suite
    if run_collection "Advanced Testing Suite" "$advanced_collection" "$env_file" "advanced"; then
        ((passed_tests++))
    else
        ((failed_tests++))
    fi
    ((total_tests++))
    log ""
    
    # Run Complete Flow Test
    if run_collection "Complete Flow Test" "$flow_collection" "$env_file" "flow"; then
        ((passed_tests++))
    else
        ((failed_tests++))
    fi
    ((total_tests++))
    log ""
    
    # Generate summary
    generate_summary
    
    # Final results
    log "${BLUE}📋 Final Test Results${NC}"
    log "${BLUE}===================${NC}"
    log "Total Collections: $total_tests"
    log "${GREEN}Passed: $passed_tests${NC}"
    log "${RED}Failed: $failed_tests${NC}"
    
    if [ $failed_tests -eq 0 ]; then
        log ""
        log "${GREEN}🎉 All tests passed successfully! 🎉${NC}"
        log "${GREEN}The Watch Party API is working correctly.${NC}"
        exit 0
    else
        log ""
        log "${RED}⚠️  Some tests failed. Please check the reports for details.${NC}"
        log "${YELLOW}Check the HTML reports in: $RESULTS_DIR${NC}"
        exit 1
    fi
}

# Handle script arguments
case "${1:-}" in
    "basic")
        log "${BLUE}Running Basic API tests only...${NC}"
        check_prerequisites
        run_collection "Basic API" "$POSTMAN_DIR/Watch-Party-API-Collection.json" \
            "$POSTMAN_DIR/environments/Local-Development.postman_environment.json" "api"
        ;;
    "advanced")
        log "${BLUE}Running Advanced tests only...${NC}"
        check_prerequisites
        run_collection "Advanced Testing Suite" "$POSTMAN_DIR/Watch-Party-Advanced-Tests.json" \
            "$POSTMAN_DIR/environments/Local-Development.postman_environment.json" "advanced"
        ;;
    "flow")
        log "${BLUE}Running Complete Flow test only...${NC}"
        check_prerequisites
        run_collection "Complete Flow Test" "$POSTMAN_DIR/Watch-Party-Complete-Flow.json" \
            "$POSTMAN_DIR/environments/Local-Development.postman_environment.json" "flow"
        ;;
    "help"|"-h"|"--help")
        echo "Watch Party API Test Automation Script"
        echo ""
        echo "Usage: $0 [option]"
        echo ""
        echo "Options:"
        echo "  basic      Run basic API tests only"
        echo "  advanced   Run advanced tests only"
        echo "  flow       Run complete flow test only"
        echo "  help       Show this help message"
        echo ""
        echo "With no options, runs all test collections."
        ;;
    *)
        main
        ;;
esac
