name: Collect service logs

on:
  workflow_dispatch:

jobs:
  collect-logs:
    name: Collect Docker service logs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare logs directory
        run: |
          rm -rf logs
          mkdir -p logs

      - name: Prepare environment files
        run: |
          if [ ! -f backend/.env ] && [ -f backend/.env.example ]; then
            cp backend/.env.example backend/.env
          fi
          if [ ! -f frontend/.env.local ] && [ -f frontend/.env.example ]; then
            cp frontend/.env.example frontend/.env.local
          fi

      - name: Build images
        run: docker compose build backend frontend

      - name: Start services
        run: docker compose up -d

      - name: Capture service logs
        run: |
          services=$(docker compose config --services)
          for service in $services; do
            echo "Collecting logs for ${service}"
            docker compose logs --no-color "$service" > "logs/${service}.log"
          done

      - name: Shut down services
        if: always()
        run: docker compose down

      - name: Upload logs archive
        uses: actions/upload-artifact@v4
        with:
          name: service-logs
          path: logs
          if-no-files-found: error
